In [1]:
from numpy import exp,dot,array,random

In [2]:
class NeuralNetwork:

    def __init__(self):

        random.seed(1)
        #Seed the random number generator it will generates same number every time.
        
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1 and mean 0.
        self.synaptic_weights = 2 * random.random((3, 1)) - 1



    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to normalise them between 0 and 1.

    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.

    def __sigmoid_derivative(self, x):

        return x * (1 - x)
    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.

    
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):

        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)
            

            # Calculate the error (The difference between the desired output and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
 
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment



    # The neural network thinks.

    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        inputs=inputs.astype(float)
        outputs=self.__sigmoid(dot(inputs, self.synaptic_weights))
        return outputs

In [ ]:


if __name__ == "__main__":

    #Intialise a single neuron neural network.
    neural_network = NeuralNetwork()



    # The training set. We have 4 examples, each consisting of 3 input values and 1 output value.
    training_set_inputs  = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    print("Dataset of input:")
    print(training_set_inputs)
    
    print("Dataset of output:")
    print(training_set_outputs)
    
    print("Random starting synaptic weights: ")
    print ("",+neural_network.synaptic_weights)

    # Train the neural network using a training set do it 20,000 times and make small adjustments each time.
    z=neural_network.train(training_set_inputs, training_set_outputs, 20000)

    print ("New synaptic weights after training: ")
    print  ("",+neural_network.synaptic_weights)


    # Test the neural network with a new situation.
    print("Enter the input:\n")
    
    a=str(input("Enter 1st i/p:"))
    b=str(input("Enter 2nd i/p:"))
    c=str(input("Enter 3rd i/p:"))
    
    print ("Considering new situation",a,"",b,"",c)
    print("Output is:\t")
    z=neural_network.think(array([a, b, c]))
    print (z)
    d=1
    d1=0
    
    if(z>=0.5):
        print("",a,"-",b,"-",c,"->",d)
    
    else:
        print("",a,"-",b,"-",c,"->",d1)
    



Dataset of input:
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
Dataset of output:
[[0]
 [1]
 [1]
 [0]]
Random starting synaptic weights: 
 [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New synaptic weights after training: 
 [[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Enter the input:

